# PyTorch Basic

PyTorch 기초 사용법

In [1]:
import numpy as np

import torch

In [2]:
nums = torch.arange(9)

In [3]:
nums

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
nums.shape

torch.Size([9])

In [5]:
type(nums)

torch.Tensor

In [6]:
nums.numpy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [7]:
nums.reshape(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [8]:
randoms = torch.rand((3,3))
randoms

tensor([[0.1965, 0.5302, 0.3888],
        [0.5432, 0.6771, 0.7076],
        [0.4519, 0.4636, 0.4906]])

In [9]:
zeros = torch.zeros((3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [10]:
ones = torch.ones((3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [11]:
torch.zeros_like(ones)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [12]:
zeros.size()

torch.Size([3, 3])

# Operations

PyTorch로 수학연산

In [13]:
nums

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
nums * 3

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [15]:
nums = nums.reshape((3,3))

In [16]:
nums + nums

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [17]:
torch.add(nums, 3)

tensor([[ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [21]:
result = torch.add(nums, 10)

In [22]:
result.numpy()

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

## View

In [23]:
range_nums = torch.arange(9).reshape(3,3)

In [25]:
range_nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [28]:
range_nums.view(-1) #rashape과 동일한 기능

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [30]:
range_nums.view(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

# Slice and Index

In [31]:
nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [32]:
nums[1]

tensor([3, 4, 5])

In [33]:
nums[1,1]

tensor(4)

In [34]:
nums[1:, 1:]

tensor([[4, 5],
        [7, 8]])

In [35]:
nums[1:]

tensor([[3, 4, 5],
        [6, 7, 8]])

## Compile

numpy를 torch tensor로 불러오기

In [37]:
arr = np.array([1,1,1])

In [38]:
arr

array([1, 1, 1])

In [39]:
torch.from_numpy(arr)

tensor([1, 1, 1])

In [40]:
arr_torch = torch.from_numpy(arr)

In [41]:
arr_torch.float()

tensor([1., 1., 1.])

In [42]:
device = 'cuda' if torch.cuda.is_available() else 'cpu' #gpu가 설치되어 있다면 cuda 실행

In [43]:
arr_torch.to(device)

tensor([1, 1, 1])

In [45]:
device # gpu가 없는 경우 cpu라고 출력됨.

'cpu'

# AutoGrad

In [47]:
x = torch.ones(2,2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [48]:
y = x+2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [49]:
print(y.grad_fn)

In [50]:
z = y * y * 3
out = z.mean()

In [51]:
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [52]:
out.backward()

In [53]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [55]:
print(x.requires_grad)
print((x ** 2).requires_grad)

True
True


In [56]:
with torch.no_grad():
  print((x ** 2).requires_grad)

False
